"""표준 계정과목 분류표.

path는 같은 이름이 다른 부모 아래에 있어도 구분되는 멱등 키다.
시드 엔드포인트는 이 데이터를 부모 -> 자식 순서로 생성한다.
"""

from __future__ import annotations

from dataclasses import dataclass

from moneymap.domain.account import AccountType


@dataclass(frozen=True)
class StandardAccount:
    path: tuple[str, ...]
    type: AccountType
    is_group: bool = False


STANDARD_ACCOUNTS: tuple[StandardAccount, ...] = (
    StandardAccount(("현금",), AccountType.ASSET),
    StandardAccount(("입출금통장",), AccountType.ASSET, is_group=True),
    StandardAccount(("저축·적금",), AccountType.ASSET, is_group=True),
    StandardAccount(("투자",), AccountType.ASSET, is_group=True),
    StandardAccount(("외화",), AccountType.ASSET, is_group=True),
    StandardAccount(("계약금·보증금",), AccountType.ASSET, is_group=True),
    StandardAccount(("계약금·보증금", "주거 보증금"), AccountType.ASSET),
    StandardAccount(("계약금·보증금", "예약·참가 보증금"), AccountType.ASSET),
    StandardAccount(("계약금·보증금", "자동차 계약금"), AccountType.ASSET),
    StandardAccount(("페이·선불충전",), AccountType.ASSET, is_group=True),
    StandardAccount(("신용카드",), AccountType.LIABILITY, is_group=True),
    StandardAccount(("대출",), AccountType.LIABILITY, is_group=True),
    StandardAccount(("개인채무",), AccountType.LIABILITY, is_group=True),
    StandardAccount(("급여",), AccountType.INCOME),
    StandardAccount(("이자·배당",), AccountType.INCOME),
    StandardAccount(("기타수익",), AccountType.INCOME),
    StandardAccount(("식비",), AccountType.EXPENSE, is_group=True),
    StandardAccount(("식비", "외식"), AccountType.EXPENSE),
    StandardAccount(("식비", "식료품"), AccountType.EXPENSE),
    StandardAccount(("식비", "배달"), AccountType.EXPENSE),
    StandardAccount(("교통",), AccountType.EXPENSE, is_group=True),
    StandardAccount(("교통", "대중교통"), AccountType.EXPENSE),
    StandardAccount(("교통", "택시"), AccountType.EXPENSE),
    StandardAccount(("교통", "자가용"), AccountType.EXPENSE),
    StandardAccount(("교통", "렌터카"), AccountType.EXPENSE, is_group=True),
    StandardAccount(("교통", "렌터카", "대여료"), AccountType.EXPENSE),
    StandardAccount(("교통", "렌터카", "주유·충전비"), AccountType.EXPENSE),
    StandardAccount(("교통", "렌터카", "통행료"), AccountType.EXPENSE),
    StandardAccount(("교통", "렌터카", "주차비"), AccountType.EXPENSE),
    StandardAccount(("문화·여가",), AccountType.EXPENSE, is_group=True),
    StandardAccount(("문화·여가", "여행"), AccountType.EXPENSE, is_group=True),
    StandardAccount(("문화·여가", "여행", "숙박"), AccountType.EXPENSE),
    StandardAccount(("문화·여가", "여행", "관광·체험"), AccountType.EXPENSE),
    StandardAccount(("문화·여가", "여행", "여행 준비"), AccountType.EXPENSE),
    StandardAccount(("문화·여가", "구독"), AccountType.EXPENSE, is_group=True),
    StandardAccount(("문화·여가", "구독", "영상"), AccountType.EXPENSE),
    StandardAccount(("문화·여가", "구독", "음악"), AccountType.EXPENSE),
    StandardAccount(("문화·여가", "구독", "멤버십"), AccountType.EXPENSE),
    StandardAccount(("문화·여가", "구독", "기타 구독"), AccountType.EXPENSE),
    StandardAccount(("문화·여가", "취미·오락"), AccountType.EXPENSE, is_group=True),
    StandardAccount(("문화·여가", "취미·오락", "영화·공연"), AccountType.EXPENSE),
    StandardAccount(("문화·여가", "취미·오락", "게임·PC방"), AccountType.EXPENSE),
    StandardAccount(("문화·여가", "취미·오락", "음악·창작"), AccountType.EXPENSE),
    StandardAccount(("문화·여가", "취미·오락", "스포츠·레저"), AccountType.EXPENSE),
    StandardAccount(("문화·여가", "취미·오락", "기타 취미·오락"), AccountType.EXPENSE),
    StandardAccount(("문화·여가", "복권"), AccountType.EXPENSE),
    StandardAccount(("카페·간식",), AccountType.EXPENSE),
    StandardAccount(("주거·관리비",), AccountType.EXPENSE, is_group=True),
    StandardAccount(("주거·관리비", "월세·관리비"), AccountType.EXPENSE),
    StandardAccount(("주거·관리비", "공과금"), AccountType.EXPENSE),
    StandardAccount(("주거·관리비", "이사·보관"), AccountType.EXPENSE),
    StandardAccount(("주거·관리비", "부동산 거래비용"), AccountType.EXPENSE),
    StandardAccount(("통신",), AccountType.EXPENSE),
    StandardAccount(("쇼핑·생활용품",), AccountType.EXPENSE, is_group=True),
    StandardAccount(("쇼핑·생활용품", "생활소모품"), AccountType.EXPENSE),
    StandardAccount(("쇼핑·생활용품", "가구·인테리어"), AccountType.EXPENSE),
    StandardAccount(("쇼핑·생활용품", "가전"), AccountType.EXPENSE),
    StandardAccount(("쇼핑·생활용품", "전자기기·주변기기"), AccountType.EXPENSE),
    StandardAccount(("의류",), AccountType.EXPENSE, is_group=True),
    StandardAccount(("의류", "의류·신발·잡화"), AccountType.EXPENSE),
    StandardAccount(("의류", "세탁·수선"), AccountType.EXPENSE),
    StandardAccount(("미용·관리",), AccountType.EXPENSE, is_group=True),
    StandardAccount(("미용·관리", "헤어·미용"), AccountType.EXPENSE),
    StandardAccount(("미용·관리", "목욕·사우나"), AccountType.EXPENSE),
    StandardAccount(("미용·관리", "화장품·미용용품"), AccountType.EXPENSE),
    StandardAccount(("의료·건강",), AccountType.EXPENSE, is_group=True),
    StandardAccount(("의료·건강", "진료·검진"), AccountType.EXPENSE),
    StandardAccount(("의료·건강", "정신건강"), AccountType.EXPENSE),
    StandardAccount(("의료·건강", "치과"), AccountType.EXPENSE),
    StandardAccount(("의료·건강", "약국"), AccountType.EXPENSE),
    StandardAccount(("의료·건강", "영양제"), AccountType.EXPENSE),
    StandardAccount(("의료·건강", "운동"), AccountType.EXPENSE, is_group=True),
    StandardAccount(("의료·건강", "운동", "이용료·강습"), AccountType.EXPENSE),
    StandardAccount(("의료·건강", "운동", "운동용품"), AccountType.EXPENSE),
    StandardAccount(("보험",), AccountType.EXPENSE, is_group=True),
    StandardAccount(("보험", "운전자보험"), AccountType.EXPENSE),
    StandardAccount(("보험", "주택화재보험"), AccountType.EXPENSE),
    StandardAccount(("보험", "생명·건강보험"), AccountType.EXPENSE),
    StandardAccount(("경조사·선물",), AccountType.EXPENSE, is_group=True),
    StandardAccount(("경조사·선물", "경조사"), AccountType.EXPENSE),
    StandardAccount(("경조사·선물", "선물"), AccountType.EXPENSE),
    StandardAccount(("경조사·선물", "가족 용돈·지원"), AccountType.EXPENSE),
    StandardAccount(("경조사·선물", "기부"), AccountType.EXPENSE),
    StandardAccount(("교육·자기계발",), AccountType.EXPENSE, is_group=True),
    StandardAccount(("교육·자기계발", "도서"), AccountType.EXPENSE),
    StandardAccount(("교육·자기계발", "문서 스캔"), AccountType.EXPENSE),
    StandardAccount(("교육·자기계발", "강의·코칭"), AccountType.EXPENSE),
    StandardAccount(("교육·자기계발", "스터디·모임"), AccountType.EXPENSE),
    StandardAccount(("교육·자기계발", "학력·증명서"), AccountType.EXPENSE),
    StandardAccount(("디지털 도구",), AccountType.EXPENSE, is_group=True),
    StandardAccount(("디지털 도구", "AI 서비스"), AccountType.EXPENSE),
    StandardAccount(("디지털 도구", "클라우드·호스팅"), AccountType.EXPENSE),
    StandardAccount(("디지털 도구", "소프트웨어·보안"), AccountType.EXPENSE),
    StandardAccount(("금융비용",), AccountType.EXPENSE, is_group=True),
    StandardAccount(("금융비용", "이자"), AccountType.EXPENSE),
    StandardAccount(("금융비용", "카드 연회비"), AccountType.EXPENSE),
    StandardAccount(("금융비용", "금융 수수료"), AccountType.EXPENSE),
    StandardAccount(("세금",), AccountType.EXPENSE, is_group=True),
    StandardAccount(("세금", "소득세"), AccountType.EXPENSE),
    StandardAccount(("세금", "투자세"), AccountType.EXPENSE),
    StandardAccount(("세금", "부동산세"), AccountType.EXPENSE),
    StandardAccount(("세금", "거래·인지세"), AccountType.EXPENSE),
    StandardAccount(("투자손익",), AccountType.EXPENSE, is_group=True),
    StandardAccount(("투자손익", "실현손익"), AccountType.EXPENSE),
    StandardAccount(("기타지출",), AccountType.EXPENSE),
    StandardAccount(("투자 평가손익",), AccountType.EQUITY),
    StandardAccount(("개시잔액",), AccountType.EQUITY),
)
