-- Frozen pre-account-lifecycle schema, user_version=0 (not generated by current init_db).
CREATE TABLE accounts (
 id INTEGER PRIMARY KEY, name TEXT NOT NULL, type TEXT NOT NULL,
 parent_id INTEGER REFERENCES accounts(id), currency TEXT NOT NULL DEFAULT 'KRW'
);
CREATE TABLE scenarios (
 id INTEGER PRIMARY KEY, name TEXT NOT NULL, base_scenario_id INTEGER REFERENCES scenarios(id),
 fork_date TEXT, created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE TABLE recurring_rules (
 id INTEGER PRIMARY KEY, scenario_id INTEGER NOT NULL REFERENCES scenarios(id), description TEXT NOT NULL DEFAULT '',
 from_account_id INTEGER NOT NULL REFERENCES accounts(id), to_account_id INTEGER NOT NULL REFERENCES accounts(id),
 amount INTEGER NOT NULL, currency TEXT NOT NULL DEFAULT 'KRW', schedule TEXT NOT NULL,
 start_date TEXT NOT NULL, end_date TEXT, last_materialized TEXT
);
CREATE TABLE transactions (
 id INTEGER PRIMARY KEY, scenario_id INTEGER NOT NULL REFERENCES scenarios(id), date TEXT NOT NULL,
 description TEXT NOT NULL DEFAULT '', source_rule_id INTEGER REFERENCES recurring_rules(id), posted INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE postings (
 id INTEGER PRIMARY KEY, txn_id INTEGER NOT NULL REFERENCES transactions(id) ON DELETE CASCADE,
 account_id INTEGER NOT NULL REFERENCES accounts(id), amount INTEGER NOT NULL, currency TEXT NOT NULL DEFAULT 'KRW'
);
INSERT INTO accounts(id,name,type) VALUES(1,'개시잔액','equity'),(2,'현금','asset'),(3,'월급','income');
INSERT INTO scenarios(id,name,base_scenario_id,fork_date) VALUES(1,'actual',NULL,NULL),(2,'legacy',1,'2026-09-01');
